namespace: 'movies-parser'

metadata: 
  git:
    commitId: none
  jenkins:
    buildTag: none

services:
  aws:
    account: ''
    region: ''
  registry:
    uri: 'ID.dkr.ecr.REGION.amazonaws.com'
    secret: ''

deployment:
  tag: 'develop'
  workers:
    replicas: 2